project:
  type: website
  output-dir: _site

execute:
  freeze: auto

website:
  title: "Dynamiques de la pauvreté monétaire en France"
  page-navigation: true
  site-url: "https://pierremadec.github.io/Analyses_pauvrete/"
  repo-url: "https://github.com/pierremadec/Analyses_pauvrete"
  reader-mode: false
  bread-crumbs: true
  favicon: www/fofce.png

  page-footer:
    border: true
    left: "![](/www/ccby4.png){height='16'}"
    right: "propulsé par ![](/www/quarto.png){height='16'}"

  navbar:
    title: false
    search: true
    code-tools: true
    background: "#FEFEFE"
    logo: www/ofce_m.png
    logo-alt: "OFCE"
    logo-href: "https://www.ofce.fr/"
    left:
      - text: "wp 2026-06"
        icon: house
        href: index.html
    right:
      - text: "GitHub"
        icon: github
        href: https://github.com/pierremadec/Analyses_pauvrete

comments:
  hypothesis: false

language:
  fr:
    other-links-title: "Autres formats"

other-links:
  - text: "PDF (wp)"
    href: "index.pdf"

wp: 06
annee: 2026
bibliography: references.bib
date: "2026-03-25"
date-modified: now

author:
  - name: "Pierre Madec"
    email: "pierre.madec@ofce.sciences-po.fr"
    affiliation: "OFCE, Sciences Po Paris"
    affiliation-url: "https://www.ofce.fr"

format:
  ofce-html:
    link-external-icon: true
    smooth-scroll: true
  ofce-pdf:
    keep-tex: false
